name: CI/CD Pipeline for Health Tracker Application's Frontend

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build Vue.js Application
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set Up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install

      - name: Install ChromeDriver
        run: npm install chromedriver

      - name: Build Application
        run: npm run build

      - name: Archive Build Files
        uses: actions/upload-artifact@v4
        with:
          name: Build Files
          path: dist

  test:
    name: Run End-to-End Tests
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set Up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install

      - name: Setup Chrome
        uses: browser-actions/setup-chrome@latest
        with:
          chrome-version: stable

      - name: Install ChromeDriver
        run: npm install chromedriver

      - name: Run Selenium Tests
        run: npm run test
        env:
          CHROME_BINARY_PATH: /usr/bin/google-chrome
          NODE_ENV: test

  deploy:
    name: Deploy to Netlify
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set Up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install

      - name: Build Application
        run: npm run build

      - name: Install Netlify CLI
        run: npm install -g netlify-cli

      - name: Deploy to Netlify
        run: netlify deploy --prod --dir=dist
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}

